apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: idre-secrets
  namespace: idre-core
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
scopes:
  - case-api
  - vault
  - idre-workflows
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cms-report-cron
  namespace: idre-core
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "@monthly"      # CMS monthly report trigger (<=30bd mandate enforced in workflow)
scopes:
  - idre-workflows
